# Generated by Django 4.1.5 on 2023-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Humor', 'Humor'), ('Mystery', 'Mystery'), ('Sci-Fi', 'Sci-Fi')], max_length=30),
        ),
    ]
